default_profile: default
profiles:
  default:
    directives: |
      Include @coraza.conf-recommended
      SecRuleEngine DetectionOnly
      SecRequestBodyAccess Off
      SecRequestBodyLimit 4096
      SecRequestBodyInMemoryLimit 4096
      SecRequestBodyLimitAction Reject
      SecResponseBodyAccess Off
      SecResponseBodyLimit 4096
      SecResponseBodyLimitAction Reject
      Include @crs-setup.conf.example
      SecAction "id:10000001,phase:1,pass,nolog,t:none,setvar:tx.blocking_paranoia_level=1"
      SecAction "id:10000002,phase:1,pass,nolog,t:none,setvar:tx.inbound_anomaly_score_threshold=5"
      SecAction "id:10000003,phase:1,pass,nolog,t:none,setvar:tx.outbound_anomaly_score_threshold=4"
      Include @owasp_crs/*.conf
  strict:
    directives: |
      Include @coraza.conf-recommended
      SecRuleEngine On
      SecRequestBodyAccess Off
      SecRequestBodyLimit 4096
      SecRequestBodyInMemoryLimit 4096
      SecRequestBodyLimitAction Reject
      SecResponseBodyAccess Off
      SecResponseBodyLimit 4096
      SecResponseBodyLimitAction Reject
      Include @crs-setup.conf.example
      SecAction "id:10000101,phase:1,pass,nolog,t:none,setvar:tx.blocking_paranoia_level=1"
      SecAction "id:10000102,phase:1,pass,nolog,t:none,setvar:tx.inbound_anomaly_score_threshold=5"
      SecAction "id:10000103,phase:1,pass,nolog,t:none,setvar:tx.outbound_anomaly_score_threshold=4"
      Include @owasp_crs/*.conf
