default_profile: default
profiles:
  default:
    directives: |
      Include @coraza.conf-recommended
      SecRuleEngine DetectionOnly
      SecRequestBodyAccess On
      SecRequestBodyLimit 1048576
      SecRequestBodyLimitAction Reject
      SecResponseBodyAccess On
      SecResponseBodyLimit 1048576
      SecResponseBodyLimitAction Reject
      Include @crs-setup.conf.example
      SecAction "id:10000001,phase:1,pass,nolog,t:none,setvar:tx.blocking_paranoia_level=1"
      SecAction "id:10000002,phase:1,pass,nolog,t:none,setvar:tx.inbound_anomaly_score_threshold=10"
      SecAction "id:10000003,phase:1,pass,nolog,t:none,setvar:tx.outbound_anomaly_score_threshold=8"
      Include @owasp_crs/*.conf
      SecRuleRemoveById 941130
  strict:
    directives: |
      Include @coraza.conf-recommended
      SecRuleEngine On
      SecRequestBodyAccess On
      SecRequestBodyLimit 1048576
      SecRequestBodyLimitAction Reject
      SecResponseBodyAccess On
      SecResponseBodyLimit 1048576
      SecResponseBodyLimitAction Reject
      SecResponseBodyMimeType text/plain text/html text/xml application/json
      Include @crs-setup.conf.example
      SecAction "id:10000101,phase:1,pass,nolog,t:none,setvar:tx.blocking_paranoia_level=1"
      SecAction "id:10000102,phase:1,pass,nolog,t:none,setvar:tx.inbound_anomaly_score_threshold=5"
      SecAction "id:10000103,phase:1,pass,nolog,t:none,setvar:tx.outbound_anomaly_score_threshold=4"
      SecAction "id:10000104,phase:1,pass,nolog,t:none,setvar:tx.early_blocking=1"
      Include @owasp_crs/*.conf
