apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: podinfo-waf-blocking
  namespace: demo
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: podinfo
  extProc:
    - backendRefs:
        - group: ""
          kind: Service
          name: coraza-ext-proc-block
          namespace: gateway-system
          port: 9002
      messageTimeout: 200ms
      failOpen: false
      metadata:
        accessibleNamespaces:
          - envoy-gateway
      processingMode:
        request:
          attributes:
            - xds.route_name
            - xds.route_metadata
          body: Buffered
        response:
          body: Buffered
