apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-tailscale
  namespace: observability
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - grafana-observability
  defaultBackend:
    service:
      name: kube-prometheus-stack-grafana
      port:
        number: 80
